version: '3'
services: 
  db:
    image:  postgres
    container_name: psql-container
    environment: 
      - POSTGRES_PASSWORD=postgres
    expose: 
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data  
    networks:
      - my-network
  webserver:
    build:  .
    container_name: webserver-container   
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@psql-container:5432/ubademy
    ports: 
      - "5000:8000"
    depends_on:
      - db
    networks: 
      - my-network
networks:
  my-network:
    driver: bridge
volumes:
  db-data:
    driver: local